<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <RootNamespace>Matrixsoft.PwnedPasswords</RootNamespace>
    <AssemblyName>Matrixsoft.PwnedPasswords</AssemblyName>
    <Authors>Ramesh Kumar</Authors>
    <Company>Matrixsoft</Company>
    <Product>Matrixsoft.PwnedPasswords</Product>
    <PackageId>Matrixsoft.PwnedPasswords</PackageId>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageProjectUrl>https://github.com/MatrixsoftIN/PwnedPasswords</PackageProjectUrl>
    <Copyright>Matrixsoft</Copyright>
    <Description>.NET Core Password Validator checks a password's integrity against Troy Hunt's "Have I Been Pwned" aka HIBP Passwords list. Many Thanks to @troyhunt.</Description>
    <Version>1.1.0</Version>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/MatrixsoftIN/PwnedPasswords</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
    <PackageReference Include="Microsoft.AspNetCore.Identity" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'!='netstandard2.0'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
